name: Build & Release APK

on:
  push:
    tags:
      - "v*"

jobs:
  build-debug:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      JAVA_VERSION: "17"
      BUILD_DIR: app/build/outputs/apk/debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Gradle assembleDebug
        run: ./gradlew assembleDebug --no-daemon

      - name: Locate APK
        id: locate
        run: |
          APK=$(ls $BUILD_DIR/*.apk | head -1)
          echo "apk=$APK" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ${{ steps.locate.outputs.apk }}
          if-no-files-found: error
          retention-days: 14

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: SSH Proxy ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.locate.outputs.apk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
